[recipe]
interpreter = "sh"

[[step]]
run = "patch -Np1 -i ../libxkbcommon-1.13.2-upstream_fix-1.patch"

[[step]]
run = "mkdir build && cd build"

[[step]]
run = "meson setup .. --prefix=/usr --buildtype=release -D enable-docs=false"

[[step]]
run = "ninja -j$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') / 1024 / 1024 / 2 ))"

[[step]]
run = "sudo ninja install || doas ninja install"
