curl https://gitweb.gentoo.org/repo/gentoo.git/plain/dev-libs/yajl/files/yajl-2.1.0-cmake-4.patch -o cmake-4-patch.patch
patch < cmake-4-patch.patch
./configure
sudo make install || doas make install
