[package]
name = "libstartup-notification"
version = "0.12"
description = "Reference implementation of the startup notification protocol."
[source]
src = "https://www.freedesktop.org/software/startup-notification/releases/startup-notification-0.12.tar.gz"
[dependencies]
deps = [""]

[build]
system = "autotools"
